//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalPerson.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesen_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesen_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaturalPerson.Api.Resources.ErrorMessagesen-US", typeof(ErrorMessagesen_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection cannt add.
        /// </summary>
        public static string CantAddConnection {
            get {
                return ResourceManager.GetString("CantAddConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Add Person.
        /// </summary>
        public static string CantAddPerson {
            get {
                return ResourceManager.GetString("CantAddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant delete connection.
        /// </summary>
        public static string CantDeleteError {
            get {
                return ResourceManager.GetString("CantDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Delete Person.
        /// </summary>
        public static string CantDeletePerson {
            get {
                return ResourceManager.GetString("CantDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inglisuri texti.
        /// </summary>
        public static string CantUpdatePerson {
            get {
                return ResourceManager.GetString("CantUpdatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Update Person2.
        /// </summary>
        public static string CantUpdatePerson1 {
            get {
                return ResourceManager.GetString("CantUpdatePerson1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant upload picture.
        /// </summary>
        public static string CantUploadPicture {
            get {
                return ResourceManager.GetString("CantUploadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
